// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Song struct {
	ID          pgtype.UUID
	GroupName   string
	Name        string
	ReleaseDate pgtype.Date
	Text        pgtype.Text
	Link        pgtype.Text
}
