# .golangci.yml
linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - gosimple
    - gocyclo

issues:
  exclude-dirs:
    - build
    - docs
    - logs

run:
  timeout: 1m
  tests: false
  concurrency: 4

output:
  color: true
