http:
  host: "localhost"
  port: "8080"

db:
  username: "postgres"
  host: "localhost"
  port: "5432"
  dbname: "songlibrary"
  sslmode: "disable"

repo_implement:
  engine: "postgresql"
  sqldriver: "pgx/v5"